name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Create .htaccess file
        run: |
          echo '<IfModule mod_rewrite.c>' > dist/.htaccess
          echo 'RewriteEngine On' >> dist/.htaccess
          echo 'RewriteBase /subdirectory' >> dist/.htaccess
          echo 'RewriteRule ^index\.html$ - [L]' >> dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-f' >> dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-d' >> dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-l' >> dist/.htaccess
          echo 'RewriteRule . /index.html [L]' >> dist/.htaccess
          echo '</IfModule>' >> dist/.htaccess

      - name: Push changes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'deenr'
          destination-repository-name: 'brainbase-htmlpublic'
          user-email: deenrayman@outlook.be
          target-branch: main
